baseURL = "https://sevenofi.com/"
languageCode = "en-us"
title = "Seven of I: Keeper of the Words"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2018-2024 Valerie Ryan"

[params]

  # Metadata for search engines and social sharing
  author = "Valerie Ryan"
  description = "Split is a centrally-divided layout for a professional online presence with a big image or video left with alongside content."
  shareImage = "images/sevenofi1-199x300.jpg"
  twitterHandle = "ValerieRyan7ofi"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/sevenofi1-678x1024.jpg"
      position = "sticky "

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Purchase"

      [[params.links.list1.link]]
        text = "Amazon"
        url = "https://amzn.to/2M6Rr4e"

    #   [[params.links.list1.link]]
    #     text = "Email"
    #     url = "#"

    #   [[params.links.list1.link]]
    #     text = "Newsletter"
    #     url = "#"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Connect"

      [[params.links.list2.link]]
        text = "Facebook"
        url = "https://www.facebook.com/ValerieRyanAuthor/"

      [[params.links.list2.link]]
        text = "Twitter"
        url = "https://twitter.com/ValerieRyan7ofi"


    #   [[params.links.list2.link]]
    #     text = "Dribbble"
    #     url = "#"

  # Links List #3
#   [[params.links]]
#     [params.links.list3]
#       heading = "Purchase"

#       [[params.links.list3.link]]
#         text = "Amazon"
#         url = "#"

#       [[params.links.list3.link]]
#         text = "Reviews"
#         url = "#"

    #   [[params.links.list3.link]]
    #     text = "Something Else"
    #     url = "#"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
